### ISSUE TITLE
Crash loading map directory

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#331]
### Steps to reproduce
1. `Map` → `Load map directory...`
2. Choose `/path/to/gpxsee-maps/World/Europe/FI`

### Actual behaviour
```sh
'gpxsee' terminated by signal SIGSEGV (Address boundary error)
```

### RCA
```sh
$ coredumpctl gdb
...
(gdb) bt
#0  0x00000000004e6893 in ?? ()
#1  0x0000000000444f5d in ?? ()
#2  0x0000000000493365 in ?? ()
#3  0x00000000004935d4 in ?? ()
#4  0x000000000044e887 in ?? ()
#5  0x00007f30dadfc910 in ?? () from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Core.so.5
#6  0x00007f30dba98a72 in QAction::triggered(bool) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#7  0x00007f30dba9b0a8 in QAction::activate(QAction::ActionEvent) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#8  0x00007f30dbc21492 in ?? () from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#9  0x00007f30dbc28b4a in ?? () from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#10 0x00007f30dbc29dc2 in QMenu::mouseReleaseEvent(QMouseEvent*) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#11 0x00007f30dbae127e in QWidget::event(QEvent*) () from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#12 0x00007f30dbc2c3b3 in QMenu::event(QEvent*) () from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#13 0x00007f30dba9ecef in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#14 0x00007f30dbaa7da3 in QApplication::notify(QObject*, QEvent*) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#15 0x00007f30dadc67fa in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Core.so.5
#16 0x00007f30dbaa6eb7 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#17 0x00007f30dbafc8a6 in ?? () from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#18 0x00007f30dbaff114 in ?? () from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#19 0x00007f30dba9ecef in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#20 0x00007f30dbaa7b50 in QApplication::notify(QObject*, QEvent*) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Widgets.so.5
#21 0x00007f30dadc67fa in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Core.so.5
#22 0x00007f30db3ff013 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Gui.so.5
#23 0x00007f30db4006a5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Gui.so.5
#24 0x00007f30db3d8dab in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Gui.so.5
#25 0x00007f30ca18073a in ?? ()
   from /nix/store/rqj9v6ap9l6sr7cxparf9vdx4a62fnpi-qtbase-5.15.0-bin/lib/qt-5.15.0/plugins/platforms/../../../../../xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5XcbQpa.so.5
#26 0x00007f30d7ea6c4d in g_main_context_dispatch () from /nix/store/rrk4d3mcp003z0kr8wg922ww3h1gfwq5-glib-2.66.3/lib/libglib-2.0.so.0
#27 0x00007f30d7ea6ed0 in g_main_context_iterate.isra () from /nix/store/rrk4d3mcp003z0kr8wg922ww3h1gfwq5-glib-2.66.3/lib/libglib-2.0.so.0
#28 0x00007f30d7ea6f5f in g_main_context_iteration () from /nix/store/rrk4d3mcp003z0kr8wg922ww3h1gfwq5-glib-2.66.3/lib/libglib-2.0.so.0
#29 0x00007f30dae1f6be in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Core.so.5
#30 0x00007f30dadc538b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Core.so.5
#31 0x00007f30dadcd5f0 in QCoreApplication::exec() () from /nix/store/xxfcll4nvha28alliqnxf852y5f0pmx9-qtbase-5.15.0/lib/libQt5Core.so.5
#32 0x0000000000448cfe in ?? ()
#33 0x0000000000442ad6 in ?? ()
#34 0x00007f30da57bdbd in __libc_start_main () from /nix/store/a3syww9igm49zdzq3ibzw9m8ccvsgxla-glibc-2.32/lib/libc.so.6
#35 0x0000000000443eba in ?? ()
```

## Configuration
GPXSee latest (https://github.com/tumic0/GPXSee/commit/75b8b9eab098d77d1a4895faa55614154fcfd061)
Qt 5.15.0

**Comment by tumic0** [comment]
Thank's for reporting it. It's the neverending story with the asynchronous WMS/WMTS map loading. Lets see how hard it will be to make it properly this time...
